Updated UG/DG, Junit and fix bugs
AY2223S2-CS2103-F10-3/tp pull request #151
Opened 2023-04-05 06:15 UTC by Gibson0918

2023-04-05 09:31 UTC, Statspadders requested changes
Exporting selected person contact details feature has been moved to 3.5

2023-04-05 09:31 UTC, Statspadders commented on docs/UserGuide.md
Exporting selected person contact details feature has been moved to 3.5

2023-04-07 06:08 UTC, Gibson0918 commented on docs/UserGuide.md
Thanks

2023-04-08 09:07 UTC, Statspadders approved these changes

2023-04-08 09:07 UTC, merged